import Head from 'next/head'
import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import HomeBackground from '../components/HomeBackground';








import ScrollSwipeArrow from '../components/ScrollSwipeArrow';
import { selectScroll } from '../reducers/autoScroll/autoScroll';

import { loadChange, selectLoading } from '../reducers/Loading/loadingSlice';



const HomeImages = [
  {
    id:0,
    imgSrc:`https://i.pinimg.com/originals/4c/cf/da/4ccfdaf6092dc341376e6fdb8130d09d.jpg`,
  },
  {
    id:1,
    imgSrc:`https://images6.alphacoders.com/332/332717.jpg`,
  },
  {
    id:2,
    imgSrc:`https://cdn.pixabay.com/photo/2018/08/13/03/00/lego-3602218_960_720.jpg`,
  }
  
]





export default function Home() {


  const autoScrollValue = useSelector(selectScroll);
  const dispatch= useDispatch();

  const loadValue = useSelector(selectLoading);


 

  useEffect(()=>{
    const listener = () => { 
     if(loadValue===0){
     
        dispatch(loadChange());
     } 
     }
     
     listener();
     return ()=>listener();

   },[loadValue]);
  

  const [hide,setHide] = useState(true);
  


  // I most likely might focus on creating more projects than 
  //  cleaning up the codes of files like these


  return (
     
    
     <div className='transition delay-120 duration-300 ease-in'>
      
      <Head>
        <title>Thomas Mathew Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="https://iconarchive.com/download/i54293/crountch/one-piece-jolly-roger/Luffys-flag.ico" />
       
      </Head>
     
      
      <div className='bg-black h-full fixed w-full'/> 
      
      
      <main className={`relative
       transition delay-120 duration-300 w-full bottom-0
       h-screen
       ${autoScrollValue===1 ? `translate-y-[-193vw]
          sm:translate-y-[-195vw] md:translate-y-[-196vw]
           lg:translate-y-[-195vw]` : `translate-y-[0rem]`}`}>
           
          
        {HomeImages.map((pic)=>(   
         <div key={pic.id} className="">   
         
          <HomeBackground
            hide={hide}
            setHide={setHide}
            pic={pic}
          />
          
         </div>
        ))}
      </main>
      <ScrollSwipeArrow/> 
      
      
      
      
     </div>
        
  );
}


