import Head from 'next/head'
import Image from 'next/image'

import SideNav from '../components/SideNav';

import { useState } from 'react';

import VioletBlock from '../components/VioletBlock';
import GrayBlackBlock from '../components/GrayBlackBlock';
import ScrollSwipeArrow from '../components/ScrollSwipeArrow';





export default function Home() {

  const [hide,setHide] = useState(true);


  // I most likely might focus on creating more projects than 
  //  cleaning up the codes of files like these


  return (
     
    
     <div className='relative w-[100%] h-[105rem]'>
      
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="https://iconarchive.com/download/i54293/crountch/one-piece-jolly-roger/Luffys-flag.ico" />
       
      </Head>
      

      <div className='fixed h-screen w-[100%]
        z-10'>
      <Image 
          src="https://img.freepik.com/free-photo/fun-spelled-word-with-plastic-blocks-background_53876-14686.jpg?w=1380&t=st=1666560257~exp=1666560857~hmac=e50e8a2bdc079968ad4cb2041b32bbf530ed40168ff383cb736606f08e238ab8"
          layout="fill"
          className="object-cover absolute"  
          alt=""
        />    
      <div/>
        <GrayBlackBlock/>
          
     </div>
  
      
        <ScrollSwipeArrow/>

     <div>
            <VioletBlock
               hide={hide}
               setHide={setHide}
            />
     <div>
            
      </div>
      </div>  

      </div>
  
    
  );
}


